version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - ollama
      - stable-diffusion
    restart: always

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: always

  stable-diffusion:
    image: automatic1111/stable-diffusion-webui
    ports:
      - "7860:7860"
    restart: always
